loanloanBreakdown done

diff --git a/.github/workflows/ec2-dev-deploy.yml b/.github/workflows/ec2-dev-deploy.yml
--- a/.github/workflows/ec2-dev-deploy.yml
+++ b/.github/workflows/ec2-dev-deploy.yml
@@ -97,38 +97,60 @@ jobs:
           aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
       
           echo "Fetching environment variables from S3..."
-          aws s3 cp s3://$S3_BUCKET_NAME/nkwadoma/backend/dev/nkwadoma.env nkwadoma-dev.env --region $S3_REGION
+          aws s3 cp s3://${{ env.S3_BUCKET_NAME }}/nkwadoma/backend/dev/nkwadoma.env nkwadoma-dev.env --region ${{ env.S3_REGION }}
       
+          # Pull the latest Docker image
           echo "Pulling the latest image..."
-          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
-      
+          docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/nkwadoma:alpha
+          # Free port 8768 if it's in use
           echo "Freeing port 8768 if in use..."
           sudo fuser -k 8768/tcp || true
-      
+              
+          # Check if the container exists
           if [ "$(docker ps -aq -f name=nkwadoma-container)" ]; then
-            echo "Stopping and removing existing container..."
-            docker stop nkwadoma-container || true
-            docker rm nkwadoma-container || true
+             echo "Stopping and removing existing container..."
+             docker stop nkwadoma-container || true
+             docker rm nkwadoma-container || true
+             echo "Stopped and removed containers."
           fi
-      
+              
+          # Run the new container
           echo "Starting the new container..."
           docker run -d --name nkwadoma-container -p 8768:8768 \
               --env-file nkwadoma-dev.env \
-              $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/nkwadoma:alpha
-              # $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG              
-          echo "Cleaning up unused Docker resources..."
+              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/nkwadoma:alpha
+          echo "Container started successfully!"
+          # Clean up unused Docker resources without affecting running containers
+          echo "Performing safe Docker cleanup..."
           docker system prune -af --filter "until=24h" || true
       
           EOF
-
 
   send_notification:
     name: Send Email Notification
     needs: [build-and-push, deploy]
     runs-on: ubuntu-latest
     if: always()
+  
     steps:
-      - name: Send success email notification
+      - uses: actions/checkout@v3
+
+      - name: Set environment variables
+        run: |
+          PROJECT_NAME="NKWADOMA"
+          echo "TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
+          if [ -n "${{ github.head_ref }}" ]; then
+            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
+          else
+            echo "BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
+          fi
+          echo "COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an <%ae>')" >> $GITHUB_ENV
+          sanitized_commit_message=$(git log -1 --pretty=%B | tr -d '\n' | tr -d '\r')
+          echo "COMMIT_MESSAGE=${sanitized_commit_message}" >> $GITHUB_ENV
+          commit_message_summary=$(git log -1 --pretty=%s | tr -d '\n' | tr -d '\r')
+          CUSTOM_TAG="${PROJECT_NAME}-${BRANCH_NAME}-${commit_message_summary// /_}"
+          echo "TAG=${CUSTOM_TAG}" >> $GITHUB_ENV
+      - name: Send build success email notification
         if: success()
         env:
           SMTP_SERVER: semicolon.africa
@@ -144,8 +166,13 @@ jobs:
             "$SMTP_USERNAME" \
             "$SMTP_PASSWORD" \
             "${{ env.EMAILS }}" \
-            "Success Notification"
-      - name: Send failure email notification
+            "${{ env.TAG }}" \
+            "${{ env.BRANCH_NAME }}" \
+            "${{ env.COMMIT_AUTHOR }}" \
+            "BUILD_REPORT_URL_SET" \
+            "AUTOMATION_TEST_URL_SET" \
+            "${{ env.COMMIT_MESSAGE }}"
+      - name: Send build failure email notification
         if: failure()
         env:
           SMTP_SERVER: semicolon.africa
@@ -161,4 +188,9 @@ jobs:
             "$SMTP_USERNAME" \
             "$SMTP_PASSWORD" \
             "${{ env.EMAILS }}" \
-            "Failure Notification"
+            "${{ env.TAG }}" \
+            "${{ env.BRANCH_NAME }}" \
+            "${{ env.COMMIT_AUTHOR }}" \
+            "BUILD_REPORT_URL_SET" \
+            "AUTOMATION_TEST_URL_SET" \
+            "${{ env.COMMIT_MESSAGE }}"
